### ISSUE TITLE
Config gateway: ValueError: Use APIFactory.init(…) to initialize APIFactory

### ISSUE THREAD

**Issue by rubenvdham** [moroen/ikea-tradfri#4]
I try to set up the software as follows:

```
$ ./tradfri config gateway 192.168.2.190 <KEY>                                                                                                                                                                           
Traceback (most recent call last):
  File "/opt/ikea-tradfri/./tradfri", line 162, in <module>
    config.handle_config_command(args)
  File "/opt/ikea-tradfri/ikeatradfri/config.py", line 101, in handle_config_command
    loop.run_until_complete(create_psk(args))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/ikea-tradfri/ikeatradfri/config.py", line 77, in create_psk
    api_factory = APIFactory(host=args.IP, psk_id=identity)
  File "/usr/lib/python3.9/site-packages/pytradfri-7.1.1-py3.9.egg/pytradfri/api/aiocoap_api.py", line 32, in __init__
    raise ValueError("Use APIFactory.init(…) to initialize APIFactory")
ValueError: Use APIFactory.init(…) to initialize APIFactory
```
 What am I missing?

**Comment by rubenvdham** [comment]
Just read deprecation notice, please remove this issue
